# This file was generated by GoReleaser. DO NOT EDIT.
cask "tools" do
  name "tools"
  desc "A bookmark manager for your terminal commands"
  homepage "https://github.com/fgeck/tools"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tools"

  on_macos do
    on_intel do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "00a3e481b16d471d111c43c428242a94c0375b1702eaa52c6c12c877f80516e1"
    end
    on_arm do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "895a3c005b60a7ba157a9fd477482aeae1b9322b1226b2b02a4ad34e7bd43e31"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_linux_amd64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "9593942a0b4af0f27a1648deb2c86473304ce287ca1f6573512e84d928ba055e"
    end
    on_arm do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_linux_arm64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "49797a9fa4cb10ee86efe2598bbbace4bbcf739e7277c67e8b3a5f4c83647999"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tools"]
    end
  end

  # No zap stanza required
end
