# This file was generated by GoReleaser. DO NOT EDIT.
cask "tools" do
  name "tools"
  desc "A bookmark manager for your terminal commands"
  homepage "https://github.com/fgeck/tools"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tools"

  on_macos do
    on_intel do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "9db109e6ddce04894befd85528a05a5e943589ccfc56c6c673e00f1ea2cba6ab"
    end
    on_arm do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "a1e4377d4468b059d16b387bee38a22ce57d6f200e726ea7993b9da428746f8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_linux_amd64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "f28fafc520fcb2d1beffe4eaeae290875f275ca5c93b1e3e6441cf1adda8633f"
    end
    on_arm do
      url "https://github.com/fgeck/tools/releases/download/v#{version}/tools_#{version}_linux_arm64.tar.gz",
        verified: "github.com/fgeck/tools"
      sha256 "84e1307a3f302b02d3416d34a499e5facbe6cbcff3576ca3f3affa43ba7364f2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tools"]
    end
  end

  # No zap stanza required
end
